### ISSUE TITLE
Congratulations with great model!

### ISSUE THREAD

**Issue by dmikushin** [jonatasgrosman/wav2vec2-sprint#6]
Hi @jonatasgrosman , great work on speech to text model on huggingface! I've tested one webinar recording in English not by native-speakers. Your model is the only one that works, while speechbrain and facebook just produce garbage.

What would be really interesting to know is how your model could be tuned further. For example, I've noticed no GPU support is offered for transcription - where and how should I add it, do you have any pointers?

Also, I've noticed submission of multiple 2min audio tracks at once does not resolve the memory problem. The memory consumption is only becomes acceptable if I submit one 2min track at a time. Therefore, it's unclear what is the intended use of audio tracks being passed as a list.

**Comment by jonatasgrosman** [comment]
Hi @dmikushin, sorry for the very late reply. I had some health issues that forced me to stay offline for a while. My life is going back to normal slowly now...

This repository is now deprecated in favor of https://github.com/jonatasgrosman/huggingsound. Using this new tool, you'll be able to fine-tune my models further if you wanna, and maybe the other issues were fixed there too. So you can try to use that new tool, and if you still have some problems, please open an issue there, and I'll try to help you.

**Comment by dmikushin** [comment]
Hi @jonatasgrosman thank you so much for letting me know, I will go to test your new work! Wish you to stay healthy and full of energy!
